import { Clock3, Flame, Search, SlidersHorizontal, Sparkles } from 'lucide-react'
import { useMemo, useState, type FocusEvent } from 'react'
import { categories, placeFeatures, type Category, type Place, type PlaceFeature } from '../types'
import CategoryIcon from './CategoryIcon'

const mainCategories: Category[] = ['Baden', 'Natur', 'Aussicht', 'Sport', 'Essen']
const readRecent = () => { try { return JSON.parse(localStorage.getItem('explorerx.recent-searches') || '[]') as string[] } catch { return [] } }

export default function Filters({ query, onQuery, category, onCategory, features, onFeature, places = [], compactCategories = false, placeholder = 'Suche nach Orten, Aktivitäten oder Städten', quickSuggestions = [], onQuickSuggestion }: { query: string; onQuery: (v: string) => void; category: Category | 'Alle'; onCategory: (v: Category | 'Alle') => void; features?: Set<PlaceFeature>; onFeature?: (v: PlaceFeature) => void; places?: Place[]; compactCategories?: boolean; placeholder?: string; quickSuggestions?: Array<{ label: string; value: string }>; onQuickSuggestion?: (value: string) => void }) {
  const [focused, setFocused] = useState(false); const [recent, setRecent] = useState<string[]>(readRecent)
  const live = useMemo(() => places.filter((place) => !query || `${place.name} ${place.category} ${place.address || ''}`.toLowerCase().includes(query.toLowerCase())).slice(0, 3), [places, query])
  const trending = useMemo(() => [...places].sort((a, b) => b.likes_count - a.likes_count).slice(0, 3), [places])
  const selectSearch = (value: string) => { onQuery(value); const next = [value, ...recent.filter((item) => item !== value)].slice(0, 4); setRecent(next); localStorage.setItem('explorerx.recent-searches', JSON.stringify(next)); setFocused(false) }
  const leave = (event: FocusEvent<HTMLDivElement>) => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setFocused(false) }
  const visibleCategories = compactCategories ? mainCategories : categories
  return <div className={`filters ${focused ? 'search-active' : ''}`} onFocusCapture={() => setFocused(true)} onBlurCapture={leave}><label className="search-box"><Search size={21}/><input value={query} onChange={(e) => onQuery(e.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && query.trim()) selectSearch(query.trim()) }} placeholder={placeholder} aria-label="Orte suchen"/><span className="search-shortcut">⌘ K</span></label>{focused && <div className="search-spotlight" role="listbox" aria-label="Suchvorschläge"><section><h3><Clock3/> Zuletzt gesucht</h3>{recent.length ? recent.map((item) => <button type="button" key={item} onClick={() => selectSearch(item)}>{item}</button>) : <p>Noch keine Suchen</p>}</section><section><h3><Sparkles/> Vorschläge</h3>{live.map((place) => <button type="button" className="place-suggestion" key={place.id} onClick={() => selectSearch(place.name)}>{place.image_url && <img src={place.image_url} alt="" loading="lazy"/>}<span><strong>{place.name}</strong><small>{place.address || place.category}</small></span></button>)}</section><section><h3><Flame/> Im Trend</h3>{trending.map((place) => <button type="button" key={place.id} onClick={() => selectSearch(place.name)}>{place.name}<small>{place.likes_count} Likes</small></button>)}</section></div>}{quickSuggestions.length > 0 && <div className="quick-searches" aria-label="Beliebte Suchbegriffe">{quickSuggestions.map((item) => <button type="button" key={item.label} onClick={() => onQuickSuggestion ? onQuickSuggestion(item.value) : selectSearch(item.value)}>{item.label}</button>)}</div>}<div className="primary-categories"><button type="button" className={category === 'Alle' ? 'active' : ''} onClick={() => onCategory('Alle')}><SlidersHorizontal/>Alle</button>{visibleCategories.map((item) => <button type="button" key={item} className={category === item ? 'active' : ''} onClick={() => onCategory(item)}><CategoryIcon category={item}/>{item}</button>)}</div>{features && onFeature && <details className="advanced-filters"><summary><SlidersHorizontal/> Mehr Filter <span>{features.size || ''}</span></summary><div className="feature-filters" aria-label="Erweiterte Filter">{placeFeatures.map((item) => <button type="button" key={item} className={features.has(item) ? 'active' : ''} aria-pressed={features.has(item)} onClick={() => onFeature(item)}>{item}</button>)}</div></details>}</div>
}
